# Generated by Django 4.2.7 on 2023-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2')], default=(1, '1'), null=True, verbose_name='рейтинг'),
        ),
    ]
